{{- if .Values.mediaServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "droppr.fullname" . }}-media-server
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "droppr.mediaServer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mediaServer.service.type }}
  ports:
  - port: {{ .Values.mediaServer.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "droppr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: media-server
{{- end }}
