{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "droppr.fullname" . }}-nginx
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "droppr.nginx.labels" . | nindent 4 }}
  {{- with .Values.nginx.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  {{- if .Values.nginx.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.nginx.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: {{ .Values.nginx.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.nginx.service.httpsPort }}
    targetPort: https
    protocol: TCP
    name: https
  selector:
    {{- include "droppr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }}
