{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "droppr.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "droppr.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    {{- include "droppr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
